In [3]:
import polars as pl
vacancy = pl.read_parquet("/home/jovyan/shares/SR004.nfs2/amaksimova/exp/hh_recsys_vacancies.pq")

In [4]:
import pandas as pd
desc = pd.read_json("/home/jovyan/shares/SR004.nfs2/amaksimova/exp/desc_clear.jsonl")
desc

                                                      desc
0        Обязанности:  Осуществлять контроль за соблюде...
1        Возможно, наша вакансия именно та, которую ты ...
2        Обязанности:  Расчет заработной платы (в том ч...
3        Для каждого, кто хочет работать и зарабатывать...
4        Компания ТД "Оливьера"- лучший дистрибьютор ди...
...                                                    ...
2734124  Обязанности:  Сортировка и упаковка товара по ...
2734125  ОКЛАД 80 000 РУБЛЕЙ. В связи с увеличением объ...
2734126  Компания МОБИЛЬНЫЙ ДОМ - ЛИДЕР В СФЕРЕ ПРОИЗВО...
2734127  Требования:   Законченное высшее/среднее медиц...
2734128  Обязанности:  консультирование покупателей быт...

[2734129 rows x 1 columns]

In [5]:
vacancy = vacancy.to_pandas()
vacancy['description'] = list(desc['desc'])

In [6]:
names = pd.read_json('/home/jovyan/shares/SR004.nfs2/amaksimova/exp/names.jsonl')

In [7]:
vacancy

,vacancy_id,name,company.id,description,keySkills.keySkill,compensation.from,compensation.to,compensation.currencyCode,area.id,area.regionId,employment,workSchedule,workExperience
0,v_862116,Смотритель музейный,c_162972,Обязанности: Осуществлять контроль за соблюде...,"[Пользователь ПК, Работа в команде, Умение пла...",16500.0,NaN,RUR,a_4761,ar_33,full,fullDay,noExperience
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"Возможно, наша вакансия именно та, которую ты ...","[Активные продажи, Холодные продажи, Кредитные...",50000.0,NaN,RUR,a_744,ar_2,full,fullDay,noExperience
2,v_1840054,Бухгалтер (по расчету зарплаты),c_198109,Обязанности: Расчет заработной платы (в том ч...,None,50000.0,65000.0,RUR,a_6223,ar_78,full,fullDay,between3And6
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,"Для каждого, кто хочет работать и зарабатывать...",None,38500.0,42000.0,RUR,a_4795,ar_51,full,fullDay,noExperience
4,v_312507,Торговый представитель (г. Абакан),c_206699,"Компания ТД ""Оливьера""- лучший дистрибьютор ди...","[Продуктивность, Клиентоориентированность, Упр...",60000.0,NaN,RUR,a_6837,ar_4,full,fullDay,between1And3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734124,v_2484959,Сборщик-упаковщик,c_203256,Обязанности: Сортировка и упаковка товара по ...,"[Пользователь ПК, Умение работать в команде, У...",40000.0,90000.0,RUR,a_5387,ar_71,full,flexible,noExperience
2734125,v_205163,Сварщик на полуавтомат,c_158695,ОКЛАД 80 000 РУБЛЕЙ. В связи с увеличением объ...,"[Желание работать и зарабатывать, Высокая энер...",80000.0,130000.0,RUR,a_5527,ar_69,full,fullDay,between1And3
2734126,v_639897,Главный инженер / Технический директор,c_209365,Компания МОБИЛЬНЫЙ ДОМ - ЛИДЕР В СФЕРЕ ПРОИЗВО...,"[Контроль исправности оборудования, Инженерные...",200000.0,NaN,RUR,a_1756,ar_41,full,fullDay,between1And3
2734127,v_1636531,"Провизор/Фармацевт (г.Адыгейск, 20 км от Красн...",c_246244,Требования: Законченное высшее/среднее медиц...,"[Предпечатная подготовка, Статистический анализ]",25000.0,NaN,RUR,a_3403,ar_60,full,fullDay,noExperience
2734128,v_1689739,Продавец-консультант в магазин бытовой техники,c_73191,Обязанности: консультирование покупателей быт...,"[1С: Торговля, Грамотная речь, Консультативные...",25000.0,NaN,RUR,a_1690,ar_91,full,fullDay,between1And3

In [8]:
vacancy['name'] = list(names['clean_names'])

In [9]:
vacancy

,vacancy_id,name,company.id,description,keySkills.keySkill,compensation.from,compensation.to,compensation.currencyCode,area.id,area.regionId,employment,workSchedule,workExperience
0,v_862116,Смотритель музейный,c_162972,Обязанности: Осуществлять контроль за соблюде...,"[Пользователь ПК, Работа в команде, Умение пла...",16500.0,NaN,RUR,a_4761,ar_33,full,fullDay,noExperience
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"Возможно, наша вакансия именно та, которую ты ...","[Активные продажи, Холодные продажи, Кредитные...",50000.0,NaN,RUR,a_744,ar_2,full,fullDay,noExperience
2,v_1840054,Бухгалтер,c_198109,Обязанности: Расчет заработной платы (в том ч...,None,50000.0,65000.0,RUR,a_6223,ar_78,full,fullDay,between3And6
3,v_2346232,Пекарь,c_6137,"Для каждого, кто хочет работать и зарабатывать...",None,38500.0,42000.0,RUR,a_4795,ar_51,full,fullDay,noExperience
4,v_312507,Торговый представитель,c_206699,"Компания ТД ""Оливьера""- лучший дистрибьютор ди...","[Продуктивность, Клиентоориентированность, Упр...",60000.0,NaN,RUR,a_6837,ar_4,full,fullDay,between1And3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734124,v_2484959,Сборщик-упаковщик,c_203256,Обязанности: Сортировка и упаковка товара по ...,"[Пользователь ПК, Умение работать в команде, У...",40000.0,90000.0,RUR,a_5387,ar_71,full,flexible,noExperience
2734125,v_205163,Сварщик на полуавтомат,c_158695,ОКЛАД 80 000 РУБЛЕЙ. В связи с увеличением объ...,"[Желание работать и зарабатывать, Высокая энер...",80000.0,130000.0,RUR,a_5527,ar_69,full,fullDay,between1And3
2734126,v_639897,Главный инженер,c_209365,Компания МОБИЛЬНЫЙ ДОМ - ЛИДЕР В СФЕРЕ ПРОИЗВО...,"[Контроль исправности оборудования, Инженерные...",200000.0,NaN,RUR,a_1756,ar_41,full,fullDay,between1And3
2734127,v_1636531,Фармацевт,c_246244,Требования: Законченное высшее/среднее медиц...,"[Предпечатная подготовка, Статистический анализ]",25000.0,NaN,RUR,a_3403,ar_60,full,fullDay,noExperience
2734128,v_1689739,Продавец-консультант в магазин бытовой техники,c_73191,Обязанности: консультирование покупателей быт...,"[1С: Торговля, Грамотная речь, Консультативные...",25000.0,NaN,RUR,a_1690,ar_91,full,fullDay,between1And3

In [30]:
df = vacancy.groupby('name').agg({'description':lambda x: list(x)})
df

                                                                                          description
name
                                                    [Для каждого, кто хочет работать и зарабатыват...
!Токарь 4,5 разряд!                                 [Обязанности: 1. Изготовление деталей различно...
""Специалист call-центра""                          [Мой Мир — крупнейший оператор DRTV-продаж на ...
"Вело-курьер"                                       [  Приглашаем к сотрудничеству. Еженедельный д...
"Грузчик", "Разнорабочий", "Сборщик-Комплектовщ...  [Обязанности:  требуются "Грузчики" требуются ...
...                                                                                               ...
️Администратор вычислительной сети                  [Привет! Мы ТМК++ (прием сотрудников осуществл...
️Главный системный администратор                    [Привет! Мы ТМК++ (прием сотрудников осуществл...
️Контент-менеджер                                   [Legalbet – СМИ международного уровня. Мы пише...
️Ученик мастеpа пo рeмoнту компьютернoй техники     [Обязанности:   Сpoчно тpeбуетcя ❗️Ученик маст...
𓆉 Менеджер по работе с клиентами                    [ˑ ˑ ✬ˑ ˑ ˑ ˑ∗ ˑ ˑ *ˑ ˑ ₊ˎˑ ˑ ˑ ✫ˑ ˑ ˑ ✬ˑ ˑ ˑ ...

[432967 rows x 1 columns]

In [32]:
df = df.reset_index()
df

,name,description
0,,"[Для каждого, кто хочет работать и зарабатыват..."
1,"!Токарь 4,5 разряд!",[Обязанности: 1. Изготовление деталей различно...
2,"""""Специалист call-центра""""",[Мой Мир — крупнейший оператор DRTV-продаж на ...
3,"""Вело-курьер""",[ Приглашаем к сотрудничеству. Еженедельный д...
4,"""Грузчик"", ""Разнорабочий"", ""Сборщик-Комплектов...","[Обязанности: требуются ""Грузчики"" требуются ..."
...,...,...
432962,️Администратор вычислительной сети,[Привет! Мы ТМК++ (прием сотрудников осуществл...
432963,️Главный системный администратор,[Привет! Мы ТМК++ (прием сотрудников осуществл...
432964,️Контент-менеджер,[Legalbet – СМИ международного уровня. Мы пише...
432965,️Ученик мастеpа пo рeмoнту компьютернoй техники,[Обязанности: Сpoчно тpeбуетcя ❗️Ученик маст...
432966,𓆉 Менеджер по работе с клиентами,[ˑ ˑ ✬ˑ ˑ ˑ ˑ∗ ˑ ˑ *ˑ ˑ ₊ˎˑ ˑ ˑ ✫ˑ ˑ ˑ ✬ˑ ˑ ˑ ...

In [34]:
result = df[df['description'].apply(lambda x: len(x) > 1)]
result

,name,description
0,,"[Для каждого, кто хочет работать и зарабатыват..."
4,"""Грузчик"", ""Разнорабочий"", ""Сборщик-Комплектов...","[Обязанности: требуются ""Грузчики"" требуются ..."
6,"""Оператор call-центра"" Удаленно Частичная заня...",[ПРИГЛАШАЕМ В КОМАНДУ! Компания «ХомТелеком24»...
7,"""Оператор центра поддержки клиентов РЖД""",[Компания ТрансТелеКом (ТТК) входит в пятерку ...
8,"""Специалист call-центра""",[Супер-условия: Официальное оформление с перв...
...,...,...
432940,​​​​​​​Контролер ОТК на производство,"[Привет, наш будущий коллега! Компания NEOVOLT..."
432941,​​​​​​​Менеджер IT-проектов в КЭДО,[Мы - Компания Тензор. С 1996 года создаем и в...
432948,​​​​​​​Руководитель ​​​​​​​отдела продукта жил...,"[Общество с ограниченной ответственностью ""А10..."
432949,​​​​​​​Старший мастер нефтебазы,[В Транспортно-складском цеху в г. Кировск Мур...
432962,️Администратор вычислительной сети,[Привет! Мы ТМК++ (прием сотрудников осуществл...

In [40]:
desc = list(result['description'])
ddd=[]
for i in range(len(desc)):
    q = [w.split(" ")[0] for w in desc[i]]
    qq = []
    for j in range(len(desc[i])):
        if q.count(desc[i][j].split(" ")[0])<=1:
            qq.append(desc[i][j])
    if len(qq):
        ddd.append(qq)

In [44]:
dd = pd.DataFrame()
query = []
pos = []
for i in ddd:
    if len(i)>1:
        query.append(i[0])
        pos.append(i[1::])
dd['query'] = query
dd['pos'] = pos
dd

,query,pos
0,Супер-условия: Официальное оформление с перво...,[ПРИГЛАШАЕМ В КОМАНДУ! Компания «ХомТелеком24»...
1,"AURIGA – аккредитованная IT-компания, оказываю...",[Компания - Freemake - разработчик мультимедиа...
2,Недавно мы запустили новый продукт в крипто те...,[О нас: Мы занимаемся разработкой и поддержкой...
3,Команда GoodZon отвечает за разработку сервиса...,[Наш проект: Развитие сайта. Необходимо будет ...
4,"ФЕНИКС - финансово-технологическая компания, з...",[Стремление к совершенству у нас в ДНК. С 1993...
...,...,...
47894,Обязанности:- контроль выполнения планово-пред...,[Мы молодая активная и профессиональная команд...
47895,"ЧЕМ ПРЕДСТОИТ ЗАНИМАТЬСЯ Устанавливать, настр...",[Обязанности: Обеспечение установки аппаратн...
47896,"Чем предстоит заниматься Устанавливать, настр...","[ЧЕМ ПРЕДСТОИТ ЗАНИМАТЬСЯ Устанавливать, наст..."
47897,Уважаемые соискатели! Холдинг ЗУБР с 1996 г. з...,[«ЭКСПОФОРУМ-ИНТЕРНЭШНЛ» – один из ведущих игр...
47898,ПРОСЬБА УКАЗЫВАТЬ В СОПРОВОДИТЕЛЬНОМ ПИСЬМЕ ФИ...,[Компания Техпромторг является официальным дил...

In [45]:
dd.to_json('/home/jovyan/shares/SR004.nfs2/amaksimova/exp/10/tune_cool_data.jsonl',index=True)