In [275]:
import pandas as pd
import numpy as np
import requests
from tqdm import tqdm
import time
import json

In [276]:
data = pd.read_csv('../data/vacancies_ru.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

,vacancy_id,name,company_id,keySkills,compensation_from,compensation_to,compensation_currencyCode,area_id,area_regionId,employment,workSchedule,workExperience,clean_name,area_regionId_encoder,area_id_encoder,company_id_encoder,employment_encoder,workSchedule_encoder,workExperience_encoder
0,v_862116,Смотритель музейный,c_162972,"['Пользователь ПК', 'Работа в команде', 'Умени...",16500.0,NaN,RUR,a_4761,ar_33,full,fullDay,noExperience,Смотритель музейный,32,4181,69972,5,5,1
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"['Активные продажи', 'Холодные продажи', 'Кред...",50000.0,NaN,RUR,a_744,ar_2,full,fullDay,noExperience,Ведущий менеджер по работе с физическими лицами,17,6731,120750,5,5,1
2,v_1840054,Бухгалтер (по расчету зарплаты),c_198109,NaN,50000.0,65000.0,RUR,a_6223,ar_78,full,fullDay,between3And6,Бухгалтер,81,5806,109013,5,5,3
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,NaN,38500.0,42000.0,RUR,a_4795,ar_51,full,fullDay,noExperience,Пекарь,52,4218,235992,5,5,1
4,v_312507,Торговый представитель (г. Абакан),c_206699,"['Продуктивность', 'Клиентоориентированность',...",60000.0,NaN,RUR,a_6837,ar_4,full,fullDay,between1And3,Торговый представитель,39,6487,118557,5,5,2

In [277]:
data['clean_vacancy_id'] = data['vacancy_id'].str.replace('v_', '')
data.head()

,vacancy_id,name,company_id,keySkills,compensation_from,compensation_to,compensation_currencyCode,area_id,area_regionId,employment,workSchedule,workExperience,clean_name,area_regionId_encoder,area_id_encoder,company_id_encoder,employment_encoder,workSchedule_encoder,workExperience_encoder,clean_vacancy_id
0,v_862116,Смотритель музейный,c_162972,"['Пользователь ПК', 'Работа в команде', 'Умени...",16500.0,NaN,RUR,a_4761,ar_33,full,fullDay,noExperience,Смотритель музейный,32,4181,69972,5,5,1,862116
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"['Активные продажи', 'Холодные продажи', 'Кред...",50000.0,NaN,RUR,a_744,ar_2,full,fullDay,noExperience,Ведущий менеджер по работе с физическими лицами,17,6731,120750,5,5,1,288642
2,v_1840054,Бухгалтер (по расчету зарплаты),c_198109,NaN,50000.0,65000.0,RUR,a_6223,ar_78,full,fullDay,between3And6,Бухгалтер,81,5806,109013,5,5,3,1840054
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,NaN,38500.0,42000.0,RUR,a_4795,ar_51,full,fullDay,noExperience,Пекарь,52,4218,235992,5,5,1,2346232
4,v_312507,Торговый представитель (г. Абакан),c_206699,"['Продуктивность', 'Клиентоориентированность',...",60000.0,NaN,RUR,a_6837,ar_4,full,fullDay,between1And3,Торговый представитель,39,6487,118557,5,5,2,312507

In [278]:
# все коды проф ролей и областей
    
url = f'https://api.hh.ru/professional_roles'

response = requests.get(url)

if response.status_code == 200:
    res = response.json()['categories']

In [279]:
prof_area_codes = {}

for r in res:
    prof_area_codes[r['id']] = r['name']

print(prof_area_codes)


with open('prof_area_codes.json', 'w') as file:
    json.dump(prof_area_codes, file)

{'19': 'Автомобильный бизнес', '5': 'Административный персонал', '15': 'Безопасность', '26': 'Высший и средний менеджмент', '8': 'Добыча сырья', '16': 'Домашний, обслуживающий персонал', '14': 'Закупки', '11': 'Информационные технологии', '24': 'Искусство, развлечения, массмедиа', '6': 'Маркетинг, реклама, PR', '23': 'Медицина, фармацевтика', '25': 'Наука, образование', '1': 'Продажи, обслуживание клиентов', '7': 'Производство, сервисное обслуживание', '17': 'Рабочий персонал', '2': 'Розничная торговля', '9': 'Сельское хозяйство', '21': 'Спортивные клубы, фитнес, салоны красоты', '4': 'Стратегия, инвестиции, консалтинг', '22': 'Страхование', '18': 'Строительство, недвижимость', '10': 'Транспорт, логистика, перевозки', '20': 'Туризм, гостиницы, рестораны', '12': 'Управление персоналом, тренинги', '3': 'Финансы, бухгалтерия', '13': 'Юристы', '27': 'Другое'}

In [280]:
prof_roles_codes = {}

for r in res:
    roles = r['roles']
    for role in roles:
        prof_roles_codes[role['id']] = role['name']

print(prof_roles_codes)


with open('prof_roles_codes.json', 'w') as file:
    json.dump(prof_roles_codes, file)

{'4': 'Автомойщик', '5': 'Автослесарь, автомеханик', '62': 'Мастер-приемщик', '70': 'Менеджер по продажам, менеджер по работе с клиентами', '8': 'Администратор', '33': 'Делопроизводитель, архивариус', '58': 'Курьер', '76': 'Менеджер/руководитель АХО', '84': 'Оператор ПК, оператор базы данных', '88': 'Офис-менеджер', '93': 'Переводчик', '110': 'Секретарь, помощник руководителя, ассистент', '22': 'Военнослужащий', '90': 'Охранник', '95': 'Полицейский', '116': 'Специалист по информационной безопасности', '120': 'Специалист службы безопасности', '26': 'Генеральный директор, исполнительный директор (CEO)', '36': 'Директор по информационным технологиям (CIO)', '37': 'Директор по маркетингу и PR (CMO)', '38': 'Директор по персоналу (HRD)', '166': 'Директор юридического департамента (CLO)', '53': 'Коммерческий директор (CCO)', '80': 'Начальник производства', '87': 'Операционный директор (COO)', '157': 'Руководитель отдела аналитики', '172': 'Руководитель отдела логистики', '170': 'Руководитель отдела маркетинга и рекламы', '171': 'Руководитель отдела персонала', '161': 'Руководитель филиала', '125': 'Технический директор (CTO)', '135': 'Финансовый директор (CFO)', '27': 'Геодезист', '28': 'Геолог', '168': 'Лаборант', '63': 'Машинист', '79': 'Научный специалист, исследователь', '82': 'Начальник смены, мастер участка', '49': 'Технолог', '21': 'Водитель', '23': 'Воспитатель, няня', '32': 'Дворник', '89': 'Официант, бармен, бариста', '130': 'Уборщица, уборщик', '66': 'Менеджер по закупкам', '119': 'Специалист по тендерам', '156': 'BI-аналитик, аналитик данных', '160': 'DevOps-инженер', '10': 'Аналитик', '12': 'Арт-директор, креативный директор', '150': 'Бизнес-аналитик', '25': 'Гейм-дизайнер', '165': 'Дата-сайентист', '34': 'Дизайнер, художник', '73': 'Менеджер продукта', '155': 'Методолог', '96': 'Программист, разработчик', '164': 'Продуктовый аналитик', '104': 'Руководитель группы разработки', '107': 'Руководитель проектов', '112': 'Сетевой инженер', '113': 'Системный администратор', '148': 'Системный аналитик', '114': 'Системный инженер', '121': 'Специалист технической поддержки', '124': 'Тестировщик', '126': 'Технический писатель', '13': 'Артист, актер, аниматор', '20': 'Видеооператор, видеомонтажер', '41': 'Журналист, корреспондент', '55': 'Копирайтер, редактор, корректор', '98': 'Продюсер', '103': 'Режиссер, сценарист', '139': 'Фотограф, ретушер', '1': 'Event-менеджер', '2': 'PR-менеджер', '3': 'SMM-менеджер, контент-менеджер', '163': 'Маркетолог-аналитик', '68': 'Менеджер по маркетингу, интернет-маркетолог', '71': 'Менеджер по работе с партнерами', '99': 'Промоутер', '15': 'Ассистент врача', '19': 'Ветеринарный врач', '24': 'Врач', '29': 'Главный врач, заведующий отделением', '42': 'Заведующий аптекой', '64': 'Медицинская сестра, медицинский брат', '65': 'Медицинский представитель', '151': 'Специалист по сертификации', '133': 'Фармацевт-провизор', '17': 'Бизнес-тренер', '167': 'Методист', '101': 'Психолог', '132': 'Учитель, преподаватель, педагог', '6': 'Агент по недвижимости', '154': 'Брокер', '51': 'Кассир-операционист', '54': 'Координатор отдела продаж', '57': 'Кредитный специалист', '83': 'Оператор call-центра, специалист контактного центра', '97': 'Продавец-консультант, продавец-кассир', '105': 'Руководитель отдела клиентского обслуживания', '106': 'Руководитель отдела продаж', '122': 'Страховой агент', '129': 'Торговый представитель', '174': 'Инженер ПНР', '44': 'Инженер по качеству', '45': 'Инженер по охране труда и технике безопасности, инженер-эколог', '46': 'Инженер по эксплуатации', '48': 'Инженер-конструктор, инженер-проектировщик', '169': 'Инженер-электроник, инженер-электронщик', '144': 'Инженер-энергетик, инженер-электрик', '149': 'Контролёр ОТК', '162': 'Мастер по ремонту оборудования, техники', '152': 'Метролог', '173': 'Механик', '85': 'Оператор производственной линии', '86': 'Оператор станков с ЧПУ', '109': 'Сварщик', '111': 'Сервисный инженер, инженер-механик', '115': 'Слесарь, сантехник', '128': 'Токарь, фрезеровщик, шлифовщик', '141': 'Швея, портной, закройщик', '143': 'Электромонтажник', '31': 'Грузчик', '52': 'Кладовщик', '59': 'Маляр, штукатур', '78': 'Монтажник', '102': 'Разнорабочий', '131': 'Упаковщик, комплектовщик', '9': 'Администратор магазина, администратор торгового зала', '35': 'Директор магазина, директор сети магазинов', '77': 'Мерчандайзер', '123': 'Супервайзер', '127': 'Товаровед', '7': 'Агроном', '43': 'Зоотехник', '56': 'Косметолог', '60': 'Массажист', '61': 'Мастер ногтевого сервиса', '92': 'Парикмахер', '138': 'Фитнес-тренер, инструктор тренажерного зала', '75': 'Менеджер/консультант по стратегии', '134': 'Финансовый аналитик, инвестиционный аналитик', '11': 'Андеррайтер', '91': 'Оценщик', '14': 'Архитектор', '30': 'Главный инженер проекта', '47': 'Инженер ПТО, инженер-сметчик', '100': 'Прораб, мастер СМР', '108': 'Руководитель строительного проекта', '159': 'Бортпроводник', '39': 'Диспетчер', '67': 'Менеджер по логистике, менеджер по ВЭД', '81': 'Начальник склада', '72': 'Менеджер по туризму', '74': 'Менеджер ресторана', '94': 'Повар, пекарь, кондитер', '140': 'Хостес', '153': 'Менеджер по компенсациям и льготам', '69': 'Менеджер по персоналу', '117': 'Специалист по кадрам', '118': 'Специалист по подбору персонала', '16': 'Аудитор', '18': 'Бухгалтер', '50': 'Казначей', '158': 'Комплаенс-менеджер', '147': 'Специалист по взысканию задолженности', '136': 'Финансовый контролер', '137': 'Финансовый менеджер', '142': 'Экономист', '145': 'Юрисконсульт', '146': 'Юрист', '40': 'Другое'}

In [281]:
# маппинг областей на роли
areas_to_roles = {}

for r in res:
    areas_to_roles[r['id']] = list()
    roles = r['roles']
    for role in roles:
        areas_to_roles[r['id']].append(role['id'])
    
print(areas_to_roles)


with open('areas_to_roles.json', 'w') as file:
    json.dump(areas_to_roles, file)

{'19': ['4', '5', '62', '70'], '5': ['8', '33', '58', '76', '84', '88', '93', '110'], '15': ['22', '90', '95', '116', '120'], '26': ['26', '36', '37', '38', '166', '53', '80', '87', '157', '172', '170', '171', '161', '125', '135'], '8': ['27', '28', '168', '63', '79', '82', '49'], '16': ['8', '21', '23', '32', '58', '89', '90', '130'], '14': ['66', '119'], '11': ['156', '160', '10', '12', '150', '25', '165', '34', '36', '73', '155', '96', '164', '104', '157', '107', '112', '113', '148', '114', '116', '121', '124', '125', '126'], '24': ['12', '13', '20', '25', '34', '41', '55', '98', '103', '139'], '6': ['1', '2', '3', '10', '12', '34', '37', '55', '163', '68', '70', '71', '99', '170'], '23': ['8', '15', '19', '24', '29', '42', '168', '64', '65', '79', '151', '133'], '25': ['17', '23', '168', '167', '79', '101', '132'], '1': ['6', '10', '154', '51', '53', '54', '57', '70', '71', '83', '97', '105', '106', '161', '151', '121', '122', '129'], '7': ['174', '44', '45', '46', '48', '169', '144', '149', '168', '162', '63', '152', '173', '79', '80', '82', '85', '86', '109', '111', '115', '151', '49', '128', '141', '143'], '17': ['5', '21', '31', '52', '59', '63', '173', '78', '85', '86', '102', '109', '111', '115', '128', '131', '143'], '2': ['9', '35', '77', '97', '99', '123', '127'], '9': ['7', '19', '43', '63', '111', '49'], '21': ['8', '56', '60', '61', '70', '92', '138'], '4': ['10', '150', '75', '107', '134'], '22': ['11', '91', '122'], '18': ['6', '14', '154', '27', '30', '34', '47', '45', '46', '48', '59', '63', '78', '100', '102', '107', '108', '109', '115', '143'], '10': ['159', '21', '31', '39', '52', '58', '63', '67', '81', '172', '131'], '20': ['8', '72', '74', '76', '89', '94', '130', '140'], '12': ['17', '38', '153', '69', '171', '117', '118'], '3': ['16', '154', '18', '50', '158', '57', '155', '147', '134', '135', '136', '137', '142'], '13': ['166', '158', '145', '146'], '27': ['40']}

In [282]:
# маппинг ролей на области
roles_to_areas = {}

for area, roles in areas_to_roles.items():
    for role in roles:
        if role in roles_to_areas:
            roles_to_areas[role].append(area)
        else:
            roles_to_areas[role] = [area]

print(roles_to_areas)


with open('roles_to_areas.json', 'w') as file:
    json.dump(roles_to_areas, file)

{'4': ['19'], '5': ['19', '17'], '62': ['19'], '70': ['19', '6', '1', '21'], '8': ['5', '16', '23', '21', '20'], '33': ['5'], '58': ['5', '16', '10'], '76': ['5', '20'], '84': ['5'], '88': ['5'], '93': ['5'], '110': ['5'], '22': ['15'], '90': ['15', '16'], '95': ['15'], '116': ['15', '11'], '120': ['15'], '26': ['26'], '36': ['26', '11'], '37': ['26', '6'], '38': ['26', '12'], '166': ['26', '13'], '53': ['26', '1'], '80': ['26', '7'], '87': ['26'], '157': ['26', '11'], '172': ['26', '10'], '170': ['26', '6'], '171': ['26', '12'], '161': ['26', '1'], '125': ['26', '11'], '135': ['26', '3'], '27': ['8', '18'], '28': ['8'], '168': ['8', '23', '25', '7'], '63': ['8', '7', '17', '9', '18', '10'], '79': ['8', '23', '25', '7'], '82': ['8', '7'], '49': ['8', '7', '9'], '21': ['16', '17', '10'], '23': ['16', '25'], '32': ['16'], '89': ['16', '20'], '130': ['16', '20'], '66': ['14'], '119': ['14'], '156': ['11'], '160': ['11'], '10': ['11', '6', '1', '4'], '12': ['11', '24', '6'], '150': ['11', '4'], '25': ['11', '24'], '165': ['11'], '34': ['11', '24', '6', '18'], '73': ['11'], '155': ['11', '3'], '96': ['11'], '164': ['11'], '104': ['11'], '107': ['11', '4', '18'], '112': ['11'], '113': ['11'], '148': ['11'], '114': ['11'], '121': ['11', '1'], '124': ['11'], '126': ['11'], '13': ['24'], '20': ['24'], '41': ['24'], '55': ['24', '6'], '98': ['24'], '103': ['24'], '139': ['24'], '1': ['6'], '2': ['6'], '3': ['6'], '163': ['6'], '68': ['6'], '71': ['6', '1'], '99': ['6', '2'], '15': ['23'], '19': ['23', '9'], '24': ['23'], '29': ['23'], '42': ['23'], '64': ['23'], '65': ['23'], '151': ['23', '1', '7'], '133': ['23'], '17': ['25', '12'], '167': ['25'], '101': ['25'], '132': ['25'], '6': ['1', '18'], '154': ['1', '18', '3'], '51': ['1'], '54': ['1'], '57': ['1', '3'], '83': ['1'], '97': ['1', '2'], '105': ['1'], '106': ['1'], '122': ['1', '22'], '129': ['1'], '174': ['7'], '44': ['7'], '45': ['7', '18'], '46': ['7', '18'], '48': ['7', '18'], '169': ['7'], '144': ['7'], '149': ['7'], '162': ['7'], '152': ['7'], '173': ['7', '17'], '85': ['7', '17'], '86': ['7', '17'], '109': ['7', '17', '18'], '111': ['7', '17', '9'], '115': ['7', '17', '18'], '128': ['7', '17'], '141': ['7'], '143': ['7', '17', '18'], '31': ['17', '10'], '52': ['17', '10'], '59': ['17', '18'], '78': ['17', '18'], '102': ['17', '18'], '131': ['17', '10'], '9': ['2'], '35': ['2'], '77': ['2'], '123': ['2'], '127': ['2'], '7': ['9'], '43': ['9'], '56': ['21'], '60': ['21'], '61': ['21'], '92': ['21'], '138': ['21'], '75': ['4'], '134': ['4', '3'], '11': ['22'], '91': ['22'], '14': ['18'], '30': ['18'], '47': ['18'], '100': ['18'], '108': ['18'], '159': ['10'], '39': ['10'], '67': ['10'], '81': ['10'], '72': ['20'], '74': ['20'], '94': ['20'], '140': ['20'], '153': ['12'], '69': ['12'], '117': ['12'], '118': ['12'], '16': ['3'], '18': ['3'], '50': ['3'], '158': ['3', '13'], '147': ['3'], '136': ['3'], '137': ['3'], '142': ['3'], '145': ['13'], '146': ['13'], '40': ['27']}

In [283]:
# следующая часть (внутри ***) не используется, тк на hh.ru поменялось кодирование idшников вакансий
# и регионов, и фичу, которую я пыталась выделить, выделить для данного датасета невозможно

In [284]:
# ***

In [285]:
# токен приложения
token_hh = ''

headers = {
    'Authorization': f'Bearer {token_hh}'
}

In [286]:
id_list = data['clean_vacancy_id'].unique()
id_list

array(['862116', '288642', '1840054', ..., '639897', '1636531', '1689739'],
      dtype=object)

In [287]:
url = f'https://api.hh.ru/vacancies/2346232'

response = requests.get(url)

if response.status_code == 200:
    vac = response.json()

vac['professional_roles'][0]['id']

'93'

In [288]:
# data.drop('prof_codes', axis=1, inplace=True)

In [291]:
id_used = np.empty(shape=(0,))
id_used

array([], dtype=float64)

In [292]:
# достаю проф коды для датасета

start_time = time.time()
cnt = 0

for ind in tqdm(id_list):
    if ind in id_used:
        continue
        
    cnt += 1
    id_used = np.append(id_used, np.array(ind))

    url = f'https://api.hh.ru/vacancies/{ind}'
    
    try:
        response = requests.get(url)
    except Exception:
        continue
        
    if response.status_code != 200:
        continue
    else:
        vac = response.json()
        
        if vac['professional_roles']:
            prof_code = vac['professional_roles'][0]['id']
        else:
            continue
        
        row_id = data.index[data['clean_vacancy_id'] == str(ind)]
        
        if len(row_id) > 0:
            data.loc[row_id, 'prof_codes'] = prof_code
            
    if cnt >= 500:
        break
        
end_time = time.time()
exec_time = end_time - start_time
print('Execution time:', exec_time)

  0%|                                               | 0/2209572 [00:00<?, ?it/s]/var/folders/35/_fnsgly951b8wkst1vg_3lj40000gn/T/ipykernel_15355/3209738946.py:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if ind in id_used:
  0%|                                 | 500/2209572 [01:44<128:46:40,  4.77it/s]

Execution time: 104.93482494354248

In [293]:
data.head()

,vacancy_id,name,company_id,keySkills,compensation_from,compensation_to,compensation_currencyCode,area_id,area_regionId,employment,...,workExperience,clean_name,area_regionId_encoder,area_id_encoder,company_id_encoder,employment_encoder,workSchedule_encoder,workExperience_encoder,clean_vacancy_id,prof_codes
0,v_862116,Смотритель музейный,c_162972,"['Пользователь ПК', 'Работа в команде', 'Умени...",16500.0,NaN,RUR,a_4761,ar_33,full,...,noExperience,Смотритель музейный,32,4181,69972,5,5,1,862116,NaN
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"['Активные продажи', 'Холодные продажи', 'Кред...",50000.0,NaN,RUR,a_744,ar_2,full,...,noExperience,Ведущий менеджер по работе с физическими лицами,17,6731,120750,5,5,1,288642,NaN
2,v_1840054,Бухгалтер (по расчету зарплаты),c_198109,NaN,50000.0,65000.0,RUR,a_6223,ar_78,full,...,between3And6,Бухгалтер,81,5806,109013,5,5,3,1840054,NaN
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,NaN,38500.0,42000.0,RUR,a_4795,ar_51,full,...,noExperience,Пекарь,52,4218,235992,5,5,1,2346232,93
4,v_312507,Торговый представитель (г. Абакан),c_206699,"['Продуктивность', 'Клиентоориентированность',...",60000.0,NaN,RUR,a_6837,ar_4,full,...,between1And3,Торговый представитель,39,6487,118557,5,5,2,312507,NaN

In [294]:
cnt_non_nan = data['prof_codes'].count()
print(cnt_non_nan)

193

In [295]:
non_nan_copy = data.copy()
non_nan_copy

,vacancy_id,name,company_id,keySkills,compensation_from,compensation_to,compensation_currencyCode,area_id,area_regionId,employment,...,workExperience,clean_name,area_regionId_encoder,area_id_encoder,company_id_encoder,employment_encoder,workSchedule_encoder,workExperience_encoder,clean_vacancy_id,prof_codes
0,v_862116,Смотритель музейный,c_162972,"['Пользователь ПК', 'Работа в команде', 'Умени...",16500.0,NaN,RUR,a_4761,ar_33,full,...,noExperience,Смотритель музейный,32,4181,69972,5,5,1,862116,NaN
1,v_288642,Ведущий менеджер по работе с физическими лицами,c_208672,"['Активные продажи', 'Холодные продажи', 'Кред...",50000.0,NaN,RUR,a_744,ar_2,full,...,noExperience,Ведущий менеджер по работе с физическими лицами,17,6731,120750,5,5,1,288642,NaN
2,v_1840054,Бухгалтер (по расчету зарплаты),c_198109,NaN,50000.0,65000.0,RUR,a_6223,ar_78,full,...,between3And6,Бухгалтер,81,5806,109013,5,5,3,1840054,NaN
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,NaN,38500.0,42000.0,RUR,a_4795,ar_51,full,...,noExperience,Пекарь,52,4218,235992,5,5,1,2346232,93
4,v_312507,Торговый представитель (г. Абакан),c_206699,"['Продуктивность', 'Клиентоориентированность',...",60000.0,NaN,RUR,a_6837,ar_4,full,...,between1And3,Торговый представитель,39,6487,118557,5,5,2,312507,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2209567,v_2484959,Сборщик-упаковщик,c_203256,"['Пользователь ПК', 'Умение работать в команде...",40000.0,90000.0,RUR,a_5387,ar_71,full,...,noExperience,Сборщик-упаковщик,74,4876,114733,5,2,1,2484959,NaN
2209568,v_205163,Сварщик на полуавтомат,c_158695,"['Желание работать и зарабатывать', 'Высокая э...",80000.0,130000.0,RUR,a_5527,ar_69,full,...,between1And3,Сварщик на полуавтомат,71,5032,65219,5,5,2,205163,NaN
2209569,v_639897,Главный инженер / Технический директор,c_209365,"['Контроль исправности оборудования', 'Инженер...",200000.0,NaN,RUR,a_1756,ar_41,full,...,between1And3,Главный инженер,41,842,121520,5,5,2,639897,NaN
2209570,v_1636531,"Провизор/Фармацевт (г.Адыгейск, 20 км от Красн...",c_246244,"['Предпечатная подготовка', 'Статистический ан...",25000.0,NaN,RUR,a_3403,ar_60,full,...,noExperience,Фармацевт,62,2673,162497,5,5,1,1636531,NaN
2209571,v_1689739,Продавец-консультант в магазин бытовой техники,c_73191,"['1С: Торговля', 'Грамотная речь', 'Консультат...",25000.0,NaN,RUR,a_1690,ar_91,full,...,between1And3,Продавец-консультант в магазин бытовой техники,96,769,249127,5,5,2,1689739,NaN

In [296]:
non_nan_copy.dropna(subset=['prof_codes'], inplace=True)
# non_nan_copy.to_csv('with_cat_labels.csv')

In [298]:
non_nan_copy.head()

,vacancy_id,name,company_id,keySkills,compensation_from,compensation_to,compensation_currencyCode,area_id,area_regionId,employment,...,workExperience,clean_name,area_regionId_encoder,area_id_encoder,company_id_encoder,employment_encoder,workSchedule_encoder,workExperience_encoder,clean_vacancy_id,prof_codes
3,v_2346232,"Пекарь (Токсово, Привокзальная, 16)",c_6137,NaN,38500.0,42000.0,RUR,a_4795,ar_51,full,...,noExperience,Пекарь,52,4218,235992,5,5,1,2346232,93
8,v_839657,Подсобный рабочий (строительный объект),c_192370,"['Умение работать в команде', 'Уборка строител...",50000.0,50000.0,RUR,a_2649,ar_44,full,...,noExperience,Подсобный рабочий,44,1834,102637,5,5,1,839657,54
9,v_2485961,Домработница/Домработник,c_133807,"['Уборка, стирка, домработница, помощница по х...",65000.0,75000.0,RUR,a_1756,ar_41,full,...,moreThan6,Домработница,41,842,37567,5,5,4,2485961,48
11,v_1357202,Слесарь механосборочных работ,c_113559,"['Монтаж оборудования', 'Монтаж металлоконстру...",45000.0,125000.0,RUR,a_6324,ar_1,full,...,between1And3,Слесарь механосборочных работ,1,5918,15069,5,5,2,1357202,117
13,v_401920,Директор предприятия,c_157298,"['Деловое общение', 'Организаторские навыки', ...",100000.0,NaN,RUR,a_2755,ar_87,full,...,moreThan6,Директор предприятия,91,1952,63667,5,5,4,401920,123

In [300]:
# обновление id_used для следующей итерации
id_list_non_nan = non_nan_copy['clean_vacancy_id'].unique()
id_list_non_nan[:5]

array(['2346232', '839657', '2485961', '1357202', '401920'], dtype=object)

In [302]:
id_used = np.array(id_list_non_nan)
id_used.shape

(193,)

In [303]:
# ***

In [304]:
# вместо этого данная фича ("код профессиональной роли") будет добавлена
# при сборке realtime датасета для тестирования гипотезы о ее значимости